### ISSUE TITLE
会社の図書館にある本の一覧を見る

### ISSUE THREAD

**Issue by mongolyy** [company-library/company-library#1]
- [ ] ダミーで数冊本を登録する用のseedを用意する
- [ ] トップページに本が表示されていること
  - イメージ：https://miro.com/app/board/uXjVOAXruDY=/?moveToWidget=3458764522362371130&cot=14
  - とりあえずは全件表示でOK
  - 画像も表示される
    - サンプルは google api から取得する → こんな感じ https://labo.kon-ruri.co.jp/google-books-apis/#index_id3

## Memo
- CSRベースで実装してみる

**Comment by katakoto291** [comment]
悩んでいるところ
- CSRベースの場合の認証
- デザインをどんな感じにするか

**Comment by mongolyy** [comment]
共有ありがとうございます！

> CSRベースの場合の認証

Azure AD B2Cのjwtトークンを取得して、Hasuraで認可するのはどうでしょうか？
https://hasura.io/blog/azure-active-directory-integration-hasura-jwt-claims-mapping/

> デザインをどんな感じにするか

一旦ざっくり作る or 現在の書籍管理アプリのデザインを踏襲するというのがあると思います
デザインは後でブラッシュアップすればいいと思うので、今はざっくりでもいいかと！

**Comment by katakoto291** [comment]
> Azure AD B2Cのjwtトークンを取得して、Hasuraで認可するのはどうでしょうか？
https://hasura.io/blog/azure-active-directory-integration-hasura-jwt-claims-mapping/

共有していただいたリンクをもとに、カスタムポリシーを作成し、それによって返ってきたjwtトークンを使って、Hasura Console上で認証することはできました。
（jwtトークンに含まれるhasura認証用のroleとuserIdは決め打ち。azure functionsからもhasuraに接続できるようにする必要があるかも。）

今は、カスタムポリシーを使った場合に、next-authでログインできない部分でつまっています。
原因は、next-authを使用する場合、`emails`という配列がjwtトークンに含まれている必要があるが、現在のカスタムポリシーにそれが含まれていないから。
AADのユーザー情報からメールアドレスを取得してjwtトークンに含める方法が分かっていないです。
（これもazure functionsで返すようにする方が簡単かも？）

**Comment by mongolyy** [comment]
@katakoto291 
遅くまでお疲れ様です。

> 原因は、next-authを使用する場合、emailsという配列がjwtトークンに含まれている必要があるが、現在のカスタムポリシーにそれが含まれていないから。

次の設定で、ユーザーフローを実行してjwt tokenを取得したところ、emailsという配列は存在し、想定されるメールアドレスも返ってきてました。
![2022-08-20_01h19_28](https://user-images.githubusercontent.com/10972787/185663180-4283f51a-1d11-4bee-8ba1-50c9f8918d80.png)
![2022-08-20_01h17_15](https://user-images.githubusercontent.com/10972787/185662884-a0cdf3b8-8704-405f-a9d1-4beaf7c8d935.png)

取得できない状況をもう少し詳細に教えていただけないでしょうか？
（明日の日中は空いているので、meetで会話するのとかもWelcomeです）

**Comment by katakoto291** [comment]
AADには、ユーザーフローとカスタムポリシーがあります
https://docs.microsoft.com/ja-jp/azure/active-directory-b2c/user-flow-overview

添付画像は、ユーザーフローの方なので、取得できています。
参考リンクを基にカスタムポリシーを作成しており、そちらでは取得できなかったという状況でした。

参考リンクで、なぜカスタムポリシーを使用していたかというと、
認証結果によって、取得できるレコードに制限を加えるユースケースのためと思われます。
（参考リンクでは、usersテーブルから、そのユーザーのレコードしか取得できないように制限している）

今回はユーザーごとだったりロールだったりで取得できるレコードを制限する必要は無いと思いますので、
その制限を使用しないようにしたことで、ユーザーフローで発行したJWTでもHasuraを認証できるようにしました。
