### ISSUE TITLE
貸出の記録を残す

### ISSUE THREAD

**Issue by mongolyy** [company-library/company-library#10]
- 詳細画面を修正する必要があるかも
- ボタンを作る
- ダイアログを headless ui を使用して作る

**Comment by mongolyy** [comment]
書籍のAPIは書籍のIDを元に制御する

**Comment by katakoto291** [comment]
- urqlを使ったmutationのuseMutationの戻り値について
  - 1つ目の戻り値は、mutationの状態をUIで表示するためのオブジェクト
  - 2つ目の戻り値は、mutationの実行をするための関数

https://zenn.dev/tapioca/scraps/977454673f640d

**Comment by katakoto291** [comment]
- 返却予定日の日付入力について
  - [ここ](https://www.uxpin.com/studio/jp/blog-jp/%EF%BC%92%EF%BC%90%EF%BC%92%EF%BC%92%E5%B9%B4%E7%89%88%EF%BC%9Areact%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%83%99%E3%82%B9/)に載っていたものを簡単に見てみた
  - DatePicker的なのが標準でありそうなのはAntDぐらいのようだったので、AntDを試したが、今のDialogとの相性が悪そうで、使うならかなり大変そうだった
  - `<input type="date">`でも十分そうだったので、それを使用する

https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/date

**Comment by katakoto291** [comment]
- 日時ライブラリについて
  - [ここ](https://qiita.com/ka215/items/7810ec9121cd5fd415ba)を見て、dyjs以外という観点で、[luxon](https://moment.github.io/luxon/#/)にしてみた
  - [date-fns](https://date-fns.org/)でも良かったかもしれない

**Comment by katakoto291** [comment]
テストを作成中

**Comment by katakoto291** [comment]
### 困ったところ1
- headlesuiの`Dilaog`と`Transition`を使用しているところのテスト実行時に以下のエラーが発生

```
IntersectionObserver is not defined
ReferenceError: IntersectionObserver is not defined
```

#### 解決策
[IntersectionObserver](https://developer.mozilla.org/ja/docs/Web/API/IntersectionObserver)は、変更を監視するためのもののようで、おそらくはダイアログ表示時のアニメーション関連を監視していて、window系と同じくJestのテスト時は存在しないので、エラーになっていると思われる。

とりあえず、公式のテストと同じ様にモックしてみることで解消したので、それで対応
https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/dialog/dialog.test.tsx#L31-L35

**Comment by katakoto291** [comment]
### 困ったところ2

- next/imageを使っているところのテスト
  - srcとaltを確認したい
  - altはできるが、srcの方はうまく取れない
  - 参考：https://github.com/vercel/next.js/discussions/32325

#### 解決策
- 検討中

**Comment by katakoto291** [comment]
### 困ったところ3

- コンポーネントのテストで、子コンポーネントをモックするか、子コンポーネント内のhooksをモックするか
  - 子コンポーネントのhooksのせいでエラーが出ているのでモックしたい
