### ISSUE TITLE
[...nextauth].tsとlayout.tsxに対するテストを追加

### ISSUE THREAD

**Issue by mongolyy** [company-library/company-library#121]

**Comment by katakoto291** [comment]
必要な環境変数が未設定の場合をテストするために、`jest.resetModules()`を実行して`require('@/app/api/auth/[...nextauth]/route').authOptions`が毎回実行されるようにしている。

しかし、`prismaMock`の方もリセットされることでモックされなくなってしまうようだ。

**Comment by katakoto291** [comment]
以下を用いて解決した
https://jestjs.io/ja/docs/jest-object#jestisolatemodulesfn
