### ISSUE TITLE
感想の記録を残す

### ISSUE THREAD

**Issue by mongolyy** [company-library/company-library#14]

**Comment by katakoto291** [comment]
ユーザーと感想のひも付きはbookIdを介してなので、複数回借りた時にどうやって表示させるか

- 最新の返却履歴のみを表示する
- 全件表示するけど、最新の返却履歴のところにのみ感想を表示
- その他

**Comment by mongolyy** [comment]
返却履歴と、感想を別にしてもいいかも

**Comment by mongolyy** [comment]
![2022-11-12_13h28_33](https://user-images.githubusercontent.com/10972787/201457031-a8985035-a3fb-49e9-8fdd-14e8d9bc9a44.png)

こんな感じにする

**Comment by katakoto291** [comment]
感想テーブルにBookIDとユーザーIDのユニーク制約はないため、複数回感想を投稿するとその分が残る

検討
- 返却しなくとも、感想は投稿できるようにしたい
- 感想欄を分けたことで、上の方で挙げた、「返却履歴と感想のひも付きができない」という問題は解消されている
- 感想を1つだけにすると、複数回借りた際に、返却時のダイアログで今の感想を出すようなことも考えないといけなくなる

→なので、テーブルに制約は追加しないで、投稿した分の感想が出るようにしようと思います
