### ISSUE TITLE
dependabotかrenovateの設定を追加する

### ISSUE THREAD

**Issue by mongolyy** [company-library/company-library#184]
ライブラリのアップデートに追従するため

また、可能であればNext.js系のライブラリはグループ化してアップデートしたい

**Comment by mongolyy** [comment]
実装するのは
- dependabotのgroups
  - https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#dependabot-updates-%E3%82%92-1-%E3%81%A4%E3%81%AE-pull-request-%E3%81%AB%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E5%8C%96%E3%81%99%E3%82%8B
- renovate
  - https://docs.renovatebot.com/
どちらを正式採用するかはわからないが、とりあえず作って運用してみて評価する

**Comment by katakoto291** [comment]
Renovate の Github Apps を `company-library/company-library` にインストールしました

ダッシュボードのURL
https://developer.mend.io/github/company-library

**Comment by katakoto291** [comment]
GitHub Appインストール時に、Renovateが自動で #193 を作成してくれた
これがマージされるとデフォルトの設定でRenovateが導入できるようだ

ただ、こちらでもdependabotと同様の設定を行いたいので、そうなるように設定を変更してみる
- 週1での確認
- next系のアップデートはまとめる
- （prism系のアップデートはまとめる）
- （マイナーバージョンとパッチバージョンのアップデートはまとめる）
