### ISSUE TITLE
テーブル定義を決める

### ISSUE THREAD

**Issue by mongolyy** [company-library/company-library#22]
https://miro.com/app/board/uXjVOAXruDY=/?moveToWidget=3458764522362371266&cot=14

**Comment by mongolyy** [comment]
とりあえず基本となるテーブル２つ
```
books (
  id SERIAL PRIMARY KEY,
  title TEXT,
  isbn VARCHAR(13),
  image_url TEXT,
  created_at TIMESTAMP
)
```

```
users (
  id SERIAL PRIMARY KEY,
  email TEXT,
  name TEXT,
  image_url TEXT,
  created_at TIMESTAMP
)
```

**Comment by mongolyy** [comment]
感想と予約
```
impressions (
  id SERIAL PRIMARY KEY,
  book_id INTEGER,
  user_id INTEGER,
  impression TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
)

CONSTRAINT impressions_book_id FOREIGN KEY(book_id) REFERENCES books(id)
CONSTRAINT impressions_user_id FOREIGN KEY(user_id) REFERENCES users(id)
```

```
reservations (
  id SERIAL PRIMARY KEY,
  book_id INTEGER,
  user_id INTEGER,
  reservation_date DATE,
  created_at TIMESTAMP
)

CONSTRAINT reservations_book_id FOREIGN KEY(book_id) REFERENCES books(id)
CONSTRAINT reservations_user_id FOREIGN KEY(user_id) REFERENCES users(id)
```

**Comment by erikoyamauchi** [comment]
> books (
> 
>   id SERIAL PRIMARY KEY,
> 
>   title TEXT,
> 
>   isbn VARCHAR(13) UNIQUE,
> 
>   image_url TEXT,
> 
>   created_at TIMESTAMP
> 
> )
> 
> ```

版違いの本がisbn同一な時がありそうだなーという気がしたのでuniqueはれるかなぁ、というところが気になりはしたのですが、レアケースだし同じ本として扱っても良さそうか、と自分で納得しました。

> 要検討事項
> 
> - [ ] TIMESTAMP がいいのか TIMESTAMP WITH TIME ZONEがいいのか

あんまり考えたことなかったなーと思いながら、以下を読みつつ `TIMESTAMP WITH TIME ZONE` で良いかなぁと。
https://qiita.com/yuba/items/7852a29d63d6279c6f6e

**Comment by erikoyamauchi** [comment]
> FOREIGN KEYはON DELETE CASCADEを追加した方がいいか

これについては追加に1票で 👍

**Comment by mongolyy** [comment]
体調優れない中、ありがとうございます！！

> （例: 岩波文庫が新訳版と旧訳版で同じISBNで管理していたという話）

よくご存知ですねー
カタコトさんと会話して、ISBNが同じであれば、同じ本として扱おうと一旦しました

> あんまり考えたことなかったなーと思いながら、以下を読みつつ TIMESTAMP WITH TIME ZONE で良いかなぁと。

ありがとうございます！
TIMESTAMP WITH TIME ZONE を使おうと思います！

> これについては追加に1票で 👍

カタコトさんとも話して、追加にしようとなりました

**Comment by mongolyy** [comment]
>  created_atがいいのか、registerd_atやlending_at、returned_atなどがいいのか

カタコトさんと話してcreated_atで統一した
