### ISSUE TITLE
デザインを整える

### ISSUE THREAD

**Issue by mongolyy** [company-library/company-library#72]

**Comment by katakoto291** [comment]
23/01/28時点での画面キャプチャ
https://miro.com/app/board/uXjVOAXruDY=/?moveToWidget=3458764544590696600&cot=14

その時点の最新main
https://github.com/company-library/company-library/tree/1016266d68ea22ce3b7d8c46bb9338bbb40a96a0

**Comment by katakoto291** [comment]
23/12/23で気になったこと
- 全般
  - プロダクト名をクリックしてTOPページに遷移できない
  - タブに表示されるページタイトルが同じ

- 書籍一覧
  - 書影のサイズが本の画像によってまちまち

- 書籍詳細
  - 各項目の位置
  - アバターのアイコンサイズ

**Comment by mongolyy** [comment]
気になったことをissueにしました
#143 
#144

**Comment by mongolyy** [comment]
カタコトさんの意見をもとに、
二人で話して#145 #146 #147 #148 #149 #150 #151 #152 #153 を作成した
